server:
  port: 8020
spring:
  application:
    name: ms-hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://www.lin.com:8761/eureka/
  instance:
    prefer-ip-address: true

turbine:
  aggregator:
    clusterConfig: default
  appConfig: consumer-user1, provider-hi
  cluster-name-expression: "'default'"
  combine-host-port: true